services:
  # Servidor Web
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - game-01
  game-01:
    build:
      context: ./game-01
      dockerfile: ../docker/php.dockerfile
    volumes:
      - ./game-01:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=challenge_db
  game-02:
    build:
      context: ./game-01
      dockerfile: ../docker/php.dockerfile
    volumes:
      - ./game-02/php:/var/www/html
  # Base de Datos Ãºnica
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: challenge_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: